<?php
//CREDITOS
define('PERMISO_CREAR_CREDITO_SIMULADO', 'PERMISO_CREAR_CREDITO_SIMULADO');
define('PERMISO_EDITAR_CREDITO_SIMULADO', 'PERMISO_EDITAR_CREDITO_SIMULADO');
define('PERMISO_VER_CREDITOS_SAP', 'PERMISO_VER_CREDITOS_SAP');
define('PERMISO_LISTAR_CREDITOS_SIMULADOS', 'PERMISO_LISTAR_CREDITOS_SIMULADOS');

//USUARIOS
define('PERMISO_REGISTRAR_USUARIOS', 'PERMISO_REGISTRAR_USUARIOS');
define('PERMISO_EDITAR_USUARIOS', 'PERMISO_EDITAR_USUARIOS');
define('PERMISO_ACTIVAR_DESACTIVAR_USUARIOS', 'PERMISO_ACTIVAR_DESACTIVAR_USUARIOS');
define('PERMISO_LISTAR_USUARIOS', 'PERMISO_LISTAR_USUARIOS');
define('PERMISO_BORRAR_USUARIO', 'PERMISO_BORRAR_USUARIO');

//CREDITOS BANCARIOS
define('PERMISO_CREAR_CREDITO_BANCARIO_SIMULADO', 'PERMISO_CREAR_CREDITO_BANCARIO_SIMULADO');
define('PERMISO_EDITAR_CREDITO_BANCARIO_SIMULADO', 'PERMISO_EDITAR_CREDITO_BANCARIO_SIMULADO');
define('PERMISO_VER_LISTADO_CREDITOS_BANCARIOS_SIMULADOS', 'PERMISO_VER_LISTADO_CREDITOS_BANCARIOS_SIMULADOS');
define('PERMISO_BORRAR_CREDITO_BANCARIO_SIMULADO', 'PERMISO_BORRAR_CREDITO_BANCARIO_SIMULADO');
define('PERMISO_BORRAR_CREDITO_SIMULADO', 'PERMISO_BORRAR_CREDITO_SIMULADO');


//DESEMBOLSOS
define('PERMISO_CREAR_DESEMBOLSO_SIMULADO', 'PERMISO_CREAR_DESEMBOLSO_SIMULADO');
define('PERMISO_EDITAR_DESEMBOLSO_SIMULADO', 'PERMISO_EDITAR_DESEMBOLSO_SIMULADO');
define('PERMISO_BORRAR_DESEMBOLSO_SIMULADO', 'PERMISO_BORRAR_DESEMBOLSO_SIMULADO');
define('PERMISO_VER_LISTADO_DESEMBOLSOS_SIMULADOS', 'PERMISO_VER_LISTADO_DESEMBOLSOS_SIMULADOS');

//PARAMETRIZACIÓN
define('PERMISO_PARAMETRIZAR_DATOS', 'PERMISO_PARAMETRIZAR_DATOS');


define('ROL_ADMINISTRADOR', 1);

//TIPOS DE CREDITO
define('CREDITO_SIMULADO', 2);
define('CREDITO_REAL', 1);

//TIPOS DE DESEMBOLSO
define('DESEMBOLSO_SIMULADO', 2);
define('DESEMBOLSO_REAL', 1);

define('TEST_LOCAL', 1); //0=NO, 1=SI
/*$arrayConfig = [
    'transactionName' => 'ZMFGETINFO_DEUDA_PUBLICA',
    'BUKRS' => "GVAL",
    'connectionConfig' => [
        'ashost' => '172.16.7.76',
        'sysnr'  => '00',
        'client' => '710',
        'user' => 'HVALENCI',
        'passwd' => 'PACHITA111',
        'show_errors' => true,
        'debug' => true,
    ]
]; */


define('CONFIG_SAP_CONNECTION',[
    'ashost' => '172.16.4.11',
    'sysnr'  => '00',
    'client' => '710',
    'user' => 'USER_RFC',
    'passwd' => 'RFCVALLE00',
    'show_errors' => true,
    'debug' => true,
]);

define('CONFIG_SAP_TRANSACTION', 'ZMFGETINFO_DEUDA_PUBLICA');
define('CONFIG_SAP_BUKRS',  "GVAL");



